FROM ubuntu:18.04 AS BUILD

RUN apt-get update && apt-get install make
RUN apt-get install -y python3.7 python3-pip
RUN python3.7 -m pip install --upgrade pip
RUN apt-get install -y git

COPY . /app
WORKDIR /app

RUN git checkout $BRANCH_NAME
RUN make deps
CMD make report-minutely
